import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { fileURLToPath } from "url";
import path from "path";
import fs from "fs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/**
 * esbuild plugin: redirect Node builtin imports (with or without `node:`
 * prefix) to a tiny in-bundle shim that uses Electron's runtime `require()`.
 *
 * Why: pptxgenjs (and other libs) feature-detect Node via `process.versions
 * .node` — TRUE in Electron's renderer — and then call `await import("fs")`.
 * esbuild marks `fs` external for CJS but only converts STATIC `import` to
 * `require()`; dynamic `import("fs")` survives the bundle as a native ES
 * dynamic import, which the Obsidian renderer then tries to fetch as a URL
 * and dies with a CORS error (user report 2026-05-29: Word/PPTX export
 * silently failing while PDF works because PDF lib doesn't take the Node
 * branch).
 *
 * Fix: a virtual shim module per builtin. The dynamic `import("fs")` now
 * resolves to the shim (bundled), which does `require("fs")` at runtime —
 * works on Electron, returns `{}` on mobile so calls degrade safely instead
 * of throwing fetch errors.
 */
const shimmedBuiltins = [
    'fs', 'https', 'path', 'os', 'crypto', 'stream', 'url',
    'buffer', 'util', 'events', 'http', 'zlib', 'child_process',
    'assert', 'querystring', 'tty', 'net',
];
const shimmedBuiltinSet = new Set([
    ...shimmedBuiltins,
    ...shimmedBuiltins.map(b => `node:${b}`),
]);
const builtinShimFilter = new RegExp(
    `^(node:)?(${shimmedBuiltins.join('|')})$`,
);
const electronBuiltinShimPlugin = {
    name: 'electron-builtin-shim',
    setup(build) {
        build.onResolve({ filter: builtinShimFilter }, (args) => ({
            path: args.path.replace(/^node:/, ''),
            namespace: 'electron-builtin-shim',
        }));
        build.onLoad({ filter: /.*/, namespace: 'electron-builtin-shim' }, (args) => ({
            // CRITICAL: do NOT write the literal token `require(...)` in this
            // shim. esbuild's static scanner rewrites any bare `require(name)`
            // inside bundled code to point at the bundled module — and since
            // `name` matches a shimmed builtin, it routes back to THIS shim,
            // creating an infinite-recursion cycle that esbuild breaks by
            // returning `{}`. That silently wipes out Node built-in exports
            // (e.g. `util.inherits` undefined → officeparser cascade failure).
            // We resolve `require` through window/globalThis so the scanner
            // can't see the call site. Electron renderer with nodeIntegration
            // exposes window.require → Node's real require; mobile leaves
            // both window.require and globalThis.require undefined, so the
            // shim degrades to `{}` cleanly.
            contents: `
"use strict";
var __nodeRequire = (typeof window !== "undefined" && window.require)
    || (typeof globalThis !== "undefined" && globalThis.require)
    || null;
var m = __nodeRequire ? __nodeRequire(${JSON.stringify(args.path)}) : {};
module.exports = m;
module.exports.default = m;
`,
            loader: 'js',
        }));
    },
};

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// ── Auto-deploy ──────────────────────────────────────────────────────────────
// After a successful build, copy the plugin artifacts to the local Obsidian
// vault AND the OneDrive-synced `mobile` folder so both stay current without a
// manual copy. Each target is independently guarded: if its PARENT directory
// doesn't exist (another machine, CI), it's skipped silently — never a build
// failure. Override with AIORG_DEPLOY_TARGETS (a `;`-separated list of dirs).
const DEFAULT_DEPLOY_TARGETS = [
  "C:\\obsidian\\Second Brain\\.obsidian\\plugins\\ai-organiser",
  "C:\\Users\\User\\OneDrive\\Across Devices\\mobile",
];
const DEPLOY_TARGETS = (process.env.AIORG_DEPLOY_TARGETS
  ? process.env.AIORG_DEPLOY_TARGETS.split(";").map(s => s.trim()).filter(Boolean)
  : DEFAULT_DEPLOY_TARGETS);
// The three Obsidian plugin files. styles.css is optional — copied when present.
const DEPLOY_ARTIFACTS = ["main.js", "manifest.json", "styles.css"];

function deployArtifacts() {
  for (const target of DEPLOY_TARGETS) {
    // Only deploy where the parent already exists — avoids creating stray
    // folders on machines that don't have this vault / OneDrive layout.
    if (!fs.existsSync(path.dirname(target))) continue;
    try {
      fs.mkdirSync(target, { recursive: true });
      for (const file of DEPLOY_ARTIFACTS) {
        const src = path.join(__dirname, file);
        if (!fs.existsSync(src)) continue;
        fs.copyFileSync(src, path.join(target, file));
      }
      console.log(`Deployed plugin → ${target}`);
    } catch (err) {
      console.warn(`Deploy skipped for ${target}: ${err.message}`);
    }
  }
}

esbuild.build({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@electron/remote",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    // Exclude shimmed builtins from `external` so the plugin's onResolve
    // gets a chance to intercept them. Esbuild checks `external` BEFORE
    // running plugin resolvers — without this filter, `fs` is marked
    // external by the builtins entry and the shim never fires, leaving the
    // dynamic `import("fs")` as-is in the bundle for the renderer to choke
    // on (root cause of the 12:24 deploy still silently failing on Word
    // export).
    ...builtins.filter(b => !shimmedBuiltinSet.has(b)),
  ],
  // Replace tesseract.js (officeparser's eager OCR dependency) with a no-op
  // stub. officeparser only invokes tesseract.js when `ocr: true` is passed
  // — which we never do — but its top-level `require('tesseract.js')` chain
  // throws in the Obsidian Electron renderer (worker_threads/web-worker
  // mismatch). esbuild's `__commonJS` caches the half-initialised exports
  // object after the first throw, so subsequent `await import('officeparser')`
  // calls return a defined module where `parseOffice` is undefined — the
  // user-visible "n.parseOffice is not a function" bug. Aliasing to a stub
  // lets officeparser load cleanly. See src/stubs/tesseractNoop.cjs.
  alias: {
    "tesseract.js": path.join(__dirname, "src/stubs/tesseractNoop.cjs"),
  },
  plugins: [electronBuiltinShimPlugin],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  // Minify production builds — roughly halves main.js. Dev builds stay
  // readable for debugging with inline sourcemaps.
  minify: prod,
  treeShaking: true,
  outfile: "main.js",
  loader: {
    ".wasm": "binary",
    ".md": "text"
  }
}).then(() => {
  deployArtifacts();
}).catch(() => process.exit(1));