import { registerGenerateCommands } from './generateCommands';
import { registerClearCommands } from './clearCommands';
import { registerUtilityCommands } from './utilityCommands';
import { registerSummarizeCommands } from './summarizeCommands';
import { registerMinutesCommands } from './minutesCommands';
import { registerTranslateCommands } from './translateCommands';
import { registerSmartNoteCommands } from './smartNoteCommands';
import { registerIntegrationCommands } from './integrationCommands';
import { registerHighlightCommands } from './highlightCommands';
import { registerSemanticSearchCommands } from './semanticSearchCommands';
import { registerChatCommands } from './chatCommands';
import { registerMigrationCommands } from './migrationCommands';
import { registerDashboardCommands } from './dashboardCommands';
import { registerNotebookLMCommands } from './notebookLMCommands';
import { registerExportCommands } from './exportCommands';
import { registerCanvasCommands } from './canvasCommands';
import { registerWebReaderCommands } from './webReaderCommands';
import { registerKindleCommands } from './kindleCommands';
import { registerDigitisationCommands } from './digitisationCommands';
import { registerSketchCommands } from './sketchCommands';
import { registerFlashcardCommands } from './flashcardCommands';
import { registerResearchCommands } from './researchCommands';
import { registerEmbedScanCommands } from './embedScanCommands';
import { registerQuickPeekCommands } from './quickPeekCommands';
import { registerNewsletterCommands } from './newsletterCommands';
import { registerAudioNarrationCommands } from './audioNarrationCommands';
import { registerContextMenu } from '../ui/contextMenu';
import AIOrganiserPlugin from '../main';

export function registerCommands(plugin: AIOrganiserPlugin) {
    registerGenerateCommands(plugin);
    registerClearCommands(plugin);
    registerUtilityCommands(plugin);
    registerSummarizeCommands(plugin);
    registerMinutesCommands(plugin);
    registerTranslateCommands(plugin);
    registerSmartNoteCommands(plugin);
    registerIntegrationCommands(plugin);
    registerHighlightCommands(plugin);
    registerSemanticSearchCommands(plugin);
    registerChatCommands(plugin);
    registerMigrationCommands(plugin);
    registerDashboardCommands(plugin);
    registerNotebookLMCommands(plugin);
    registerExportCommands(plugin);
    registerCanvasCommands(plugin);
    registerWebReaderCommands(plugin);
    registerKindleCommands(plugin);
    registerDigitisationCommands(plugin);
    registerSketchCommands(plugin);
    registerFlashcardCommands(plugin);
    registerResearchCommands(plugin);
    registerEmbedScanCommands(plugin);
    registerQuickPeekCommands(plugin);
    registerNewsletterCommands(plugin);
    registerAudioNarrationCommands(plugin);
    registerContextMenu(plugin);
}
