/**
 * Presentation HTML Service
 *
 * LLM orchestration for HTML slide generation, refinement, and brand audit.
 * HTML is the source of truth — generated by LLM, previewed in iframe,
 * exported via dom-to-pptx.
 */

import type { LLMFacadeContext } from '../llmFacade';
import { summarizeText, summarizeTextStream } from '../llmFacade';
import type { Result } from '../../core/result';
import { ok, err } from '../../core/result';
import type { AuditResult, DomFix } from './presentationTypes';
import type { BrandTheme } from './brandThemeService';
import {
    buildPresentationSystemPrompt,
    buildGenerationPrompt,
    buildRefinementPrompt,
    buildBrandAuditPrompt,
    extractHtmlFromResponse,
    wrapInDocument,
} from '../prompts/presentationChatPrompts';
import { sanitizePresentation, injectCSP } from './presentationSanitizer';
import { GENERATION_TIMEOUT, REFINEMENT_TIMEOUT, AUDIT_TIMEOUT } from './presentationConstants';
import { StreamingHtmlAssembler } from './streamingHtmlAssembler';
import type { StreamingCheckpoint } from './streamingHtmlAssembler';
import { tryExtractJson } from '../../utils/responseParser';
import { logger } from '../../utils/logger';

// ── Shared LLM Task Runner (L6 fix — DRY) ──────────────────────────────────

interface HtmlTaskOptions {
    systemPrompt: string;
    userPrompt: string;
    theme: BrandTheme;
    timeoutMs: number;
    signal?: AbortSignal;
    label: string;
    language?: string;
}

async function runHtmlTask(
    context: LLMFacadeContext,
    options: HtmlTaskOptions
): Promise<Result<string>> {
    if (options.signal?.aborted) return err('Aborted');

    try {
        const fullPrompt = `${options.systemPrompt}\n\n${options.userPrompt}`;

        const result = await summarizeText(context, fullPrompt, {
            timeoutMs: options.timeoutMs,
        });

        if (options.signal?.aborted) return err('Aborted');

        if (!result.success || !result.content) {
            return err(result.error || `${options.label}: LLM returned empty response`);
        }

        const deckHtml = extractHtmlFromResponse(result.content);
        if (!deckHtml) {
            return err(`${options.label}: failed to extract HTML from response`);
        }

        // Phase 2: allowlist sanitizer replaces regex blacklist
        const sanitized = sanitizePresentation(deckHtml);
        if (!sanitized.hasDeckRoot) {
            return err(`${options.label}: Missing .deck root element`);
        }
        if (!sanitized.hasSlides) {
            return err(`${options.label}: No .slide elements found`);
        }

        const wrapped = wrapInDocument(sanitized.html, options.theme.css, options.language);
        return ok(injectCSP(wrapped));
    } catch (e) {
        const msg = e instanceof Error ? e.message : 'Unknown error';
        logger.error('Presentation', `${options.label} failed: ${msg}`);
        return err(`${options.label}: ${msg}`);
    }
}

// ── Generation ──────────────────────────────────────────────────────────────

export interface GenerateOptions {
    userQuery: string;
    noteContent?: string;
    conversationHistory?: string;
    outputLanguage?: string;
    theme: BrandTheme;
    signal?: AbortSignal;
}

export async function generateHtml(
    context: LLMFacadeContext,
    options: GenerateOptions
): Promise<Result<string>> {
    return runHtmlTask(context, {
        systemPrompt: buildPresentationSystemPrompt({
            cssTheme: options.theme.css,
            outputLanguage: options.outputLanguage,
            brandRules: options.theme.promptRules || undefined,
        }),
        userPrompt: buildGenerationPrompt({
            userQuery: options.userQuery,
            noteContent: options.noteContent,
            conversationHistory: options.conversationHistory,
        }),
        theme: options.theme,
        timeoutMs: GENERATION_TIMEOUT,
        signal: options.signal,
        label: 'Generation',
        language: options.outputLanguage,
    });
}

// ── Streaming Generation ───────────────────────────────────────────────────

export interface StreamGenerateOptions extends GenerateOptions {
    onCheckpoint: (checkpoint: StreamingCheckpoint) => void;
    debounceMs?: number;
}

export async function generateHtmlStream(
    context: LLMFacadeContext,
    options: StreamGenerateOptions
): Promise<Result<string>> {
    if (options.signal?.aborted) return err('Aborted');

    try {
        const systemPrompt = buildPresentationSystemPrompt({
            cssTheme: options.theme.css,
            outputLanguage: options.outputLanguage,
            brandRules: options.theme.promptRules || undefined,
        });
        const userPrompt = buildGenerationPrompt({
            userQuery: options.userQuery,
            noteContent: options.noteContent,
            conversationHistory: options.conversationHistory,
        });
        const fullPrompt = `${systemPrompt}\n\n${userPrompt}`;

        const assembler = new StreamingHtmlAssembler({
            cssTheme: options.theme.css,
            language: options.outputLanguage,
            onCheckpoint: options.onCheckpoint,
            debounceMs: options.debounceMs,
        });

        const result = await summarizeTextStream(
            context,
            fullPrompt,
            (chunk: string) => assembler.addChunk(chunk),
            options.signal
        );

        const streamResult = assembler.finalize();

        if (options.signal?.aborted) {
            assembler.dispose();
            return err('Aborted');
        }

        if (!result.success || !streamResult.fullResponse) {
            assembler.dispose();
            return err(result.error || 'Generation: LLM returned empty response');
        }

        const deckHtml = extractHtmlFromResponse(streamResult.fullResponse);
        if (!deckHtml) {
            return err('Generation: failed to extract HTML from response');
        }

        // Phase 2: allowlist sanitizer replaces regex blacklist
        const sanitized = sanitizePresentation(deckHtml);
        if (!sanitized.hasDeckRoot) {
            return err('Generation: Missing .deck root element');
        }
        if (!sanitized.hasSlides) {
            return err('Generation: No .slide elements found');
        }

        const wrapped = wrapInDocument(sanitized.html, options.theme.css, options.outputLanguage);
        return ok(injectCSP(wrapped));
    } catch (e) {
        const msg = e instanceof Error ? e.message : 'Unknown error';
        logger.error('Presentation', `Streaming generation failed: ${msg}`);
        return err(`Generation: ${msg}`);
    }
}

// ── Refinement ──────────────────────────────────────────────────────────────

export interface RefineOptions {
    currentHtml: string;
    userRequest: string;
    conversationHistory?: string;
    outputLanguage?: string;
    theme: BrandTheme;
    signal?: AbortSignal;
}

export async function refineHtml(
    context: LLMFacadeContext,
    options: RefineOptions
): Promise<Result<string>> {
    return runHtmlTask(context, {
        systemPrompt: buildPresentationSystemPrompt({
            cssTheme: options.theme.css,
            outputLanguage: options.outputLanguage,
            brandRules: options.theme.promptRules || undefined,
        }),
        userPrompt: buildRefinementPrompt({
            currentHtml: options.currentHtml,
            userRequest: options.userRequest,
            conversationHistory: options.conversationHistory,
        }),
        theme: options.theme,
        timeoutMs: REFINEMENT_TIMEOUT,
        signal: options.signal,
        label: 'Refinement',
        language: options.outputLanguage,
    });
}

// ── Brand Audit (H3 fix — explicit status, not fail-open) ──────────────────

export async function runBrandAudit(
    context: LLMFacadeContext,
    html: string,
    theme: BrandTheme,
    signal?: AbortSignal
): Promise<Result<AuditResult>> {
    if (signal?.aborted) return err('Aborted');

    if (!theme.auditChecklist.length) {
        return ok({ status: 'passed', passed: ['all'], violations: [] });
    }

    const prompt = buildBrandAuditPrompt(html, theme.auditChecklist);

    const result = await summarizeText(context, prompt, {
        timeoutMs: AUDIT_TIMEOUT,
    });

    if (signal?.aborted) return err('Aborted');

    if (!result.success || !result.content) {
        // H3 fix: explicit 'unavailable' status instead of pretending pass
        logger.warn('PresentationAudit', `Audit LLM call failed: ${result.error}`);
        return ok({ status: 'unavailable', passed: [], violations: [] });
    }

    const parsed = tryExtractJson(result.content);
    if (!parsed || typeof parsed !== 'object') {
        return ok({ status: 'failed', passed: [], violations: [] });
    }

    const obj = parsed as Record<string, unknown>;
    const passed = Array.isArray(obj.passed) ? obj.passed.map(String) : [];
    const violations: DomFix[] = [];

    if (Array.isArray(obj.violations)) {
        for (const v of obj.violations) {
            if (!v || typeof v !== 'object') continue;
            const fix = v as Record<string, unknown>;
            if (typeof fix.selector === 'string' && typeof fix.property === 'string' && typeof fix.value === 'string') {
                violations.push({
                    selector: fix.selector,
                    property: fix.property,
                    value: fix.value,
                    reason: typeof fix.reason === 'string' ? fix.reason : '',
                });
            }
        }
    }

    const status = violations.length > 0 ? 'violations' : 'passed';
    return ok({ status, passed, violations });
}
