/**
 * Presentation HTML Service
 *
 * LLM orchestration for HTML slide generation, refinement, and brand audit.
 * HTML is the source of truth — generated by LLM, previewed in iframe,
 * exported via dom-to-pptx.
 */

import type { LLMFacadeContext } from '../llmFacade';
import { summarizeText, summarizeTextStream } from '../llmFacade';
import type { Result } from '../../core/result';
import { ok, err } from '../../core/result';
import type {
    AuditResult, DomFix,
    SelectionScope, EditMode, EditFlags, RefineScopedOutcome,
} from './presentationTypes';
import type { BrandTheme } from './brandThemeService';
import {
    buildPresentationSystemPrompt,
    buildGenerationPrompt,
    buildRefinementPrompt,
    buildBrandAuditPrompt,
    buildScopedContentEditPrompt,
    buildScopedDesignEditPrompt,
    extractHtmlFromResponse,
    wrapInDocument,
} from '../prompts/presentationChatPrompts';
import {
    extractScopedFragment, estimateScopedPromptChars, stripEditorAnnotations,
} from './presentationDomDecorator';
import { classifyDiff } from './presentationDiff';
import type { SlideContextProvider } from './slideContextProvider';
import { sanitizePresentation, injectCSP } from './presentationSanitizer';
import {
    GENERATION_HARD_BUDGET_MS,
    REFINEMENT_HARD_BUDGET_MS,
    AUDIT_TIMEOUT,
    SCOPED_EDIT_HARD_LIMIT_CHARS,
} from './presentationConstants';
import { StreamingHtmlAssembler } from './streamingHtmlAssembler';
import type { StreamingCheckpoint } from './streamingHtmlAssembler';
import { tryExtractJson } from '../../utils/responseParser';
import { logger } from '../../utils/logger';

// ── Shared LLM Task Runner (L6 fix — DRY) ──────────────────────────────────

interface HtmlTaskOptions {
    systemPrompt: string;
    userPrompt: string;
    theme: BrandTheme;
    timeoutMs: number;
    signal?: AbortSignal;
    label: string;
    language?: string;
}

async function runHtmlTask(
    context: LLMFacadeContext,
    options: HtmlTaskOptions
): Promise<Result<string>> {
    if (options.signal?.aborted) return err('Aborted');

    try {
        const fullPrompt = `${options.systemPrompt}\n\n${options.userPrompt}`;

        const result = await summarizeText(context, fullPrompt, {
            timeoutMs: options.timeoutMs,
            signal: options.signal,
        });

        if (options.signal?.aborted) return err('Aborted');

        if (!result.success || !result.content) {
            return err(result.error || `${options.label}: LLM returned empty response`);
        }

        return processExtractedHtml(result.content, options.theme.css, options.language, options.label);
    } catch (e) {
        const msg = e instanceof Error ? e.message : 'Unknown error';
        logger.error('Presentation', `${options.label} failed: ${msg}`);
        return err(`${options.label}: ${msg}`);
    }
}

// ── Shared Post-Processing (M6 fix — DRY) ─────────────────────────────────

/** Extract → sanitize → validate → wrap → CSP pipeline shared by all generation paths. */
function processExtractedHtml(
    response: string, css: string, language?: string, label = 'Generation'
): Result<string> {
    const deckHtml = extractHtmlFromResponse(response);
    if (!deckHtml) return err(`${label}: failed to extract HTML from response`);

    const sanitized = sanitizePresentation(deckHtml);
    if (!sanitized.hasDeckRoot) return err(`${label}: Missing .deck root element`);
    if (!sanitized.hasSlides) return err(`${label}: No .slide elements found`);

    const wrapped = wrapInDocument(sanitized.html, css, language);
    return ok(injectCSP(wrapped));
}

// ── Generation ──────────────────────────────────────────────────────────────

export interface GenerateOptions {
    userQuery: string;
    noteContent?: string;
    conversationHistory?: string;
    outputLanguage?: string;
    theme: BrandTheme;
    signal?: AbortSignal;
}

export async function generateHtml(
    context: LLMFacadeContext,
    options: GenerateOptions
): Promise<Result<string>> {
    return runHtmlTask(context, {
        systemPrompt: buildPresentationSystemPrompt({
            cssTheme: options.theme.css,
            outputLanguage: options.outputLanguage,
            brandRules: options.theme.promptRules || undefined,
        }),
        userPrompt: buildGenerationPrompt({
            userQuery: options.userQuery,
            noteContent: options.noteContent,
            conversationHistory: options.conversationHistory,
        }),
        theme: options.theme,
        // Inner timeout uses HARD budget — soft-budget enforcement happens
        // in the handler-owned GenerationProgressController via options.signal.
        timeoutMs: GENERATION_HARD_BUDGET_MS,
        signal: options.signal,
        label: 'Generation',
        language: options.outputLanguage,
    });
}

// ── Streaming Generation ───────────────────────────────────────────────────

export interface StreamGenerateOptions extends GenerateOptions {
    onCheckpoint: (checkpoint: StreamingCheckpoint) => void;
    /** Fires once when the first stream chunk arrives. UI maps to a
     *  "streaming response…" status so users see progress before any
     *  slide closes. */
    onStreamStart?: () => void;
    /** Fires when a new opening `<section` is observed. Argument is the
     *  1-based count (currently building slide N). UI maps to a
     *  "building slide N…" status. */
    onSlideStart?: (slideIndex: number) => void;
    debounceMs?: number;
}

export async function generateHtmlStream(
    context: LLMFacadeContext,
    options: StreamGenerateOptions
): Promise<Result<string>> {
    if (options.signal?.aborted) return err('Aborted');

    try {
        const systemPrompt = buildPresentationSystemPrompt({
            cssTheme: options.theme.css,
            outputLanguage: options.outputLanguage,
            brandRules: options.theme.promptRules || undefined,
        });
        const userPrompt = buildGenerationPrompt({
            userQuery: options.userQuery,
            noteContent: options.noteContent,
            conversationHistory: options.conversationHistory,
        });
        const fullPrompt = `${systemPrompt}\n\n${userPrompt}`;

        const assembler = new StreamingHtmlAssembler({
            cssTheme: options.theme.css,
            language: options.outputLanguage,
            onCheckpoint: options.onCheckpoint,
            onStreamStart: options.onStreamStart,
            onSlideStart: options.onSlideStart,
            debounceMs: options.debounceMs,
        });

        // Inner safety timeout uses the HARD budget. Soft-budget enforcement
        // is owned by the caller's GenerationProgressController via options.signal —
        // using the soft budget here would crash the fetch at the exact
        // moment the extend card opens (G2 finding, Gemini gate 2026-04-20).
        // H1 fix: AbortSignal.timeout() and AbortSignal.any() are not universally available
        // (absent in older Electron/iOS WebView). Use a manual controller + clearTimeout approach.
        const timeoutController = new AbortController();
        const timeoutId = setTimeout(() => timeoutController.abort(), GENERATION_HARD_BUDGET_MS);

        const combinedController = new AbortController();
        const abortCombined = () => combinedController.abort();
        timeoutController.signal.addEventListener('abort', abortCombined);
        options.signal?.addEventListener('abort', abortCombined);

        try {
            const result = await summarizeTextStream(
                context,
                fullPrompt,
                (chunk: string) => assembler.addChunk(chunk),
                combinedController.signal
            );

            const streamResult = assembler.finalize();

            if (options.signal?.aborted) {
                return err('Aborted');
            }

            if (!result.success || !streamResult.fullResponse) {
                return err(result.error || 'Generation: LLM returned empty response');
            }

            return processExtractedHtml(streamResult.fullResponse, options.theme.css, options.outputLanguage, 'Generation');
        } finally {
            clearTimeout(timeoutId);
            timeoutController.signal.removeEventListener('abort', abortCombined);
            options.signal?.removeEventListener('abort', abortCombined);
            assembler.dispose();
        }
    } catch (e) {
        const msg = e instanceof Error ? e.message : 'Unknown error';
        logger.error('Presentation', `Streaming generation failed: ${msg}`);
        return err(`Generation: ${msg}`);
    }
}

// ── Refinement ──────────────────────────────────────────────────────────────

export interface RefineOptions {
    currentHtml: string;
    userRequest: string;
    conversationHistory?: string;
    outputLanguage?: string;
    theme: BrandTheme;
    signal?: AbortSignal;
}

export async function refineHtml(
    context: LLMFacadeContext,
    options: RefineOptions
): Promise<Result<string>> {
    return runHtmlTask(context, {
        systemPrompt: buildPresentationSystemPrompt({
            cssTheme: options.theme.css,
            outputLanguage: options.outputLanguage,
            brandRules: options.theme.promptRules || undefined,
        }),
        userPrompt: buildRefinementPrompt({
            currentHtml: options.currentHtml,
            userRequest: options.userRequest,
            conversationHistory: options.conversationHistory,
        }),
        theme: options.theme,
        // See note on generateHtml — inner timeout uses HARD budget.
        timeoutMs: REFINEMENT_HARD_BUDGET_MS,
        signal: options.signal,
        label: 'Refinement',
        language: options.outputLanguage,
    });
}

// ── Brand Audit (H3 fix — explicit status, not fail-open) ──────────────────

export async function runBrandAudit(
    context: LLMFacadeContext,
    html: string,
    theme: BrandTheme,
    signal?: AbortSignal
): Promise<Result<AuditResult>> {
    if (signal?.aborted) return err('Aborted');

    if (!theme.auditChecklist.length) {
        return ok({ status: 'passed', passed: ['all'], violations: [] });
    }

    const prompt = buildBrandAuditPrompt(html, theme.auditChecklist);

    let result;
    try {
        result = await summarizeText(context, prompt, {
            timeoutMs: AUDIT_TIMEOUT,
            signal,
        });
    } catch (e) {
        const msg = e instanceof Error ? e.message : 'Unknown error';
        logger.error('PresentationAudit', `Brand audit LLM call threw: ${msg}`);
        return ok({ status: 'unavailable', passed: [], violations: [] });
    }

    if (signal?.aborted) return err('Aborted');

    if (!result.success || !result.content) {
        // H3 fix: explicit 'unavailable' status instead of pretending pass
        logger.warn('PresentationAudit', `Audit LLM call failed: ${result.error}`);
        return ok({ status: 'unavailable', passed: [], violations: [] });
    }

    const parsed = tryExtractJson(result.content);
    if (!parsed || typeof parsed !== 'object') {
        return ok({ status: 'failed', passed: [], violations: [] });
    }

    const obj = parsed as Record<string, unknown>;
    const passed = Array.isArray(obj.passed) ? obj.passed.map(String) : [];
    const violations: DomFix[] = [];

    if (Array.isArray(obj.violations)) {
        for (const v of obj.violations) {
            if (!v || typeof v !== 'object') continue;
            const fix = v as Record<string, unknown>;
            if (typeof fix.selector === 'string' && typeof fix.property === 'string' && typeof fix.value === 'string') {
                violations.push({
                    selector: fix.selector,
                    property: fix.property,
                    value: fix.value,
                    reason: typeof fix.reason === 'string' ? fix.reason : '',
                });
            }
        }
    }

    const status = violations.length > 0 ? 'violations' : 'passed';
    return ok({ status, passed, violations });
}

// ── Scoped Refinement (slide-authoring-editing plan) ───────────────────────

export interface RefineScopedOptions {
    /** Canonical deck HTML — full document, no editor instrumentation. */
    currentHtml: string;
    scope: SelectionScope;
    mode: EditMode;
    userRequest: string;
    flags: EditFlags;
    contextProvider: SlideContextProvider;
    conversationHistory?: string;
    outputLanguage?: string;
    theme: BrandTheme;
    signal?: AbortSignal;
}

/**
 * Scoped refinement orchestrator for the targeted slide editing feature.
 *
 *   1. Gather context in parallel: web research (if enabled) + reference notes
 *   2. Preflight prompt-size check; reject when over hard limit
 *   3. Build mode-dispatched prompt (content vs design); design mode picks
 *      full-HTML vs design-summary fallback based on deck size
 *   4. Run LLM via shared runHtmlTask (sanitise + wrap)
 *   5. Strip any echoed editor annotations from canonical response
 *   6. Classify diff vs original: scope diff, out-of-scope drift, structural integrity
 *   7. Return RefineScopedOutcome — frontend renders directly
 *
 * Plan: docs/completed/slide-authoring-editing-backend.md §"Service signatures"
 */
export async function refineHtmlScoped(
    context: LLMFacadeContext,
    options: RefineScopedOptions,
): Promise<Result<RefineScopedOutcome>> {
    if (options.signal?.aborted) return err('Aborted');

    // Phase 1 — gather context (parallel, signal-aware)
    const contextResult = await gatherScopedContext(options);
    if (!contextResult.ok) return contextResult;
    const { references, webResearch } = contextResult.value;
    if (options.signal?.aborted) return err('Aborted');

    // Phase 2a — extract scoped fragment with fail-closed semantics.
    // If the selection no longer resolves (slide removed by an earlier edit,
    // element path stale after structural change), abort BEFORE the LLM call:
    // proceeding with an empty fragment tells the LLM to "modify the indicated
    // region" while showing it nothing, which silently widens scope to the
    // whole deck — exactly what the fail-closed contract on
    // `extractScopedFragment` is supposed to prevent.
    // (Gemini final-gate finding R5, 2026-04-25.)
    const scopedFragment = extractScopedFragment(options.currentHtml, options.scope);
    if (!scopedFragment) {
        return err('Scoped edit: selection no longer resolves — it may have been removed or restructured. Reselect and try again.');
    }

    // Phase 2b — preflight prompt size
    const promptChars = estimateScopedPromptChars(options.currentHtml, options.scope, options.mode, {
        references, webResearch, userRequest: options.userRequest,
    });
    if (promptChars > SCOPED_EDIT_HARD_LIMIT_CHARS) {
        return err('Scoped edit: prompt exceeds size limit — try a narrower scope or use Polish whole deck.');
    }

    const userPrompt = buildScopedPrompt(options, scopedFragment, references, webResearch);

    // Phase 3 — LLM call
    const llmResult = await runHtmlTask(context, {
        systemPrompt: buildPresentationSystemPrompt({
            cssTheme: options.theme.css,
            outputLanguage: options.outputLanguage,
            brandRules: options.theme.promptRules || undefined,
        }),
        userPrompt,
        theme: options.theme,
        timeoutMs: REFINEMENT_HARD_BUDGET_MS,
        signal: options.signal,
        label: 'Scoped edit',
        language: options.outputLanguage,
    });

    if (!llmResult.ok) return llmResult;
    if (options.signal?.aborted) return err('Aborted');

    // Phase 4 — strip any echoed editor annotations + classify diff
    // The LLM saw canonical HTML; defensive strip catches any echoed back.
    const newCanonicalHtml = stripEditorAnnotations(llmResult.value);
    const { scopeDiff, outOfScopeDrift, siblingDrift, textChangedLocations, structuralIntegrity } =
        classifyDiff(options.currentHtml, newCanonicalHtml, options.scope);

    return ok({
        newHtml: newCanonicalHtml,
        scopeDiff,
        outOfScopeDrift,
        siblingDrift,
        textChangedLocations,
        structuralIntegrity,
    });
}

/** Phase 1 — fetch web research + reference notes in parallel. */
async function gatherScopedContext(
    options: RefineScopedOptions,
): Promise<Result<{ references: string; webResearch: string }>> {
    if (options.mode !== 'content') {
        // Design mode doesn't use references or web research.
        return ok({ references: '', webResearch: '' });
    }

    try {
        const [references, webResearch] = await Promise.all([
            options.flags.references.length
                ? options.contextProvider.readReferences(options.flags.references, options.signal)
                : Promise.resolve(''),
            options.flags.webSearch
                ? options.contextProvider.fetchWebResearch(options.userRequest, options.signal)
                : Promise.resolve(''),
        ]);
        return ok({ references, webResearch });
    } catch (e) {
        const msg = e instanceof Error ? e.message : 'context gathering failed';
        logger.warn('Presentation', `Scoped edit context gathering failed: ${msg}`);
        return err(`Scoped edit: ${msg}`);
    }
}

/**
 * Phase 2 — build the mode-appropriate prompt.
 *
 * Both modes send FULL canonical HTML so the LLM can preserve unscoped
 * slides byte-for-byte (it cannot preserve what it never saw — the
 * earlier "subtree-only" optimisation produced an architectural paradox
 * caught by the Gemini final-gate review, 2026-04-25).
 *
 * Token cost: full canonical HTML, capped at SCOPED_EDIT_HARD_LIMIT_CHARS
 * by the preflight gate. Above that cap the service returns err() and
 * directs the user to Polish whole deck.
 */
function buildScopedPrompt(
    options: RefineScopedOptions,
    scopedFragment: string,
    references: string,
    webResearch: string,
): string {
    if (options.mode === 'design') {
        return buildScopedDesignEditPrompt({
            currentHtml: options.currentHtml,
            scopedFragment,
            scope: options.scope,
            userRequest: options.userRequest,
            conversationHistory: options.conversationHistory,
        });
    }

    return buildScopedContentEditPrompt({
        currentHtml: options.currentHtml,
        scopedFragment,
        scope: options.scope,
        userRequest: options.userRequest,
        references: references || undefined,
        webResearch: webResearch || undefined,
        conversationHistory: options.conversationHistory,
    });
}
