/**
 * Presentation Types
 *
 * Types for the HTML-based presentation chat feature.
 * HTML is the source of truth — generated by LLM, previewed in iframe,
 * exported via dom-to-pptx.
 */

// ── Presentation Phase (State Machine) ──────────────────────────────────────

export type PresentationPhase =
    | 'empty'
    | 'generating'
    | 'preview-ready'
    | 'refining'
    | 'exporting'
    | 'auditing'
    | 'error';

// ── Re-export shared constants ──────────────────────────────────────────────

export { MAX_VERSIONS, DECK_CLASSES, SLIDE_TYPES } from './presentationConstants';
import { MAX_VERSIONS } from './presentationConstants';

export interface PresentationVersion {
    html: string;
    userPrompt: string;
    timestamp: number;
    activeSlideIndex: number;
}

// ── Session Persistence ─────────────────────────────────────────────────────

export interface PresentationSession {
    schemaVersion: 1;
    html: string;
    versions: PresentationVersion[];
    conversation: PresentationMessage[];
    brandEnabled: boolean;
    createdAt: string;
    lastActiveAt: string;
}

export interface PresentationMessage {
    role: 'user' | 'assistant' | 'system';
    content: string;
    timestamp: number;
}

// ── DOM Fix (from Haiku brand audit) ────────────────────────────────────────

export interface DomFix {
    selector: string;
    property: string;
    value: string;
    reason: string;
}

export type AuditStatus = 'passed' | 'violations' | 'unavailable' | 'failed';

export interface AuditResult {
    status: AuditStatus;
    passed: string[];
    violations: DomFix[];
}

// ── Quality ─────────────────────────────────────────────────────────────────

export type FindingSeverity = 'HIGH' | 'MEDIUM' | 'LOW';

export interface QualityFinding {
    slideIndex?: number;
    issue: string;
    suggestion: string;
    severity: FindingSeverity;
}

export interface QualityResult {
    structureScore: number;
    auditScore: number;
    totalScore: number;
    findings: QualityFinding[];
}

// ── Deterministic Quality Checks (run on iframe DOM) ────────────────────────

export interface SlideInfo {
    index: number;
    headingText: string;
    textLength: number;
    hasNotes: boolean;
    type: string;
}

export function extractSlideInfo(doc: Document): SlideInfo[] {
    const slides = doc.querySelectorAll('.slide');
    const infos: SlideInfo[] = [];
    slides.forEach((slide, i) => {
        const heading = slide.querySelector('h1, h2');
        const notes = slide.querySelector('.speaker-notes');
        const type = slide.classList.contains('slide-title') ? 'title'
            : slide.classList.contains('slide-section') ? 'section'
            : slide.classList.contains('slide-closing') ? 'closing'
            : 'content';
        infos.push({
            index: i,
            headingText: heading?.textContent?.trim() || '',
            textLength: (slide.textContent || '').length - (notes?.textContent || '').length,
            hasNotes: !!notes && (notes.textContent || '').trim().length > 0,
            type,
        });
    });
    return infos;
}

export function runStructureChecks(slides: SlideInfo[]): QualityFinding[] {
    const findings: QualityFinding[] = [];

    if (slides.length < 3) {
        findings.push({ issue: 'Deck has fewer than 3 slides', suggestion: 'Add more content', severity: 'MEDIUM' });
    }
    if (slides.length > 30) {
        findings.push({ issue: 'Deck has more than 30 slides', suggestion: 'Consider condensing', severity: 'MEDIUM' });
    }

    const seenHeadings = new Set<string>();
    for (const slide of slides) {
        if (slide.type === 'content' && slide.textLength < 20) {
            findings.push({ slideIndex: slide.index, issue: `Slide ${slide.index + 1} appears empty`, suggestion: 'Add content', severity: 'HIGH' });
        }
        if (slide.type === 'content' && slide.textLength > 800) {
            findings.push({ slideIndex: slide.index, issue: `Slide ${slide.index + 1} is overloaded (${slide.textLength} chars)`, suggestion: 'Split into multiple slides', severity: 'MEDIUM' });
        }
        if (!slide.headingText && slide.type === 'content') {
            findings.push({ slideIndex: slide.index, issue: `Slide ${slide.index + 1} has no heading`, suggestion: 'Add a heading', severity: 'MEDIUM' });
        }
        if (slide.type === 'content' && !slide.hasNotes) {
            findings.push({ slideIndex: slide.index, issue: `Slide ${slide.index + 1} has no speaker notes`, suggestion: 'Add speaker notes', severity: 'LOW' });
        }
        const normalized = slide.headingText.toLowerCase();
        if (normalized && seenHeadings.has(normalized)) {
            findings.push({ slideIndex: slide.index, issue: `Duplicate heading: "${slide.headingText}"`, suggestion: 'Use unique headings', severity: 'MEDIUM' });
        }
        if (normalized) seenHeadings.add(normalized);
    }

    return findings;
}

export function computeQualityScore(structureFindings: QualityFinding[], auditViolationCount: number): QualityResult {
    const penalty: Record<FindingSeverity, number> = { HIGH: 10, MEDIUM: 5, LOW: 2 };

    let structureScore = 50;
    for (const f of structureFindings) {
        structureScore -= penalty[f.severity];
    }

    const auditScore = Math.max(0, 50 - auditViolationCount * 8);

    return {
        structureScore: Math.max(0, structureScore),
        auditScore,
        totalScore: Math.max(0, structureScore) + auditScore,
        findings: structureFindings,
    };
}

// ── Session Migration ───────────────────────────────────────────────────────

export function migratePresentationSession(data: unknown): PresentationSession | null {
    if (!data || typeof data !== 'object') return null;
    const o = data as Record<string, unknown>;
    if (o.schemaVersion !== 1) return null;
    if (typeof o.html !== 'string' || !o.html) return null;

    // Validate and filter versions (M10 fix)
    const rawVersions = Array.isArray(o.versions) ? o.versions : [];
    const versions: PresentationVersion[] = rawVersions
        .filter((v): v is PresentationVersion =>
            !!v && typeof v === 'object'
            && typeof (v).html === 'string'
            && typeof (v).timestamp === 'number'
        )
        .slice(0, MAX_VERSIONS);

    // Validate conversation messages
    const rawConv = Array.isArray(o.conversation) ? o.conversation : [];
    const conversation: PresentationMessage[] = rawConv
        .filter((m): m is PresentationMessage =>
            !!m && typeof m === 'object'
            && typeof (m).role === 'string'
            && typeof (m).content === 'string'
        );

    return {
        schemaVersion: 1,
        html: o.html,
        versions,
        conversation,
        brandEnabled: typeof o.brandEnabled === 'boolean' ? o.brandEnabled : false,
        createdAt: typeof o.createdAt === 'string' ? o.createdAt : new Date().toISOString(),
        lastActiveAt: typeof o.lastActiveAt === 'string' ? o.lastActiveAt : new Date().toISOString(),
    };
}
